sudo: required
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  chrome: stable
language: ruby
rvm:
  - 2.6.3
script:
  - bundle install --jobs 3 --retry 3
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - postgresql
  - xvfb